default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  host: localhost
  username: postgres
  password: 07082020

development:
  <<: *default
  database: ecommerce_development

test:
  <<: *default
  database: ecommerce_test

production:
  <<: *default
  database: ecommerce_production
